server:
  port: 8083

spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:testDB3
    driverClassName: org.h2.Driver
    username: root
    password: root@123
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
